# Generated by Django 3.2.19 on 2023-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
