# Generated by Django 3.2.19 on 2023-05-08 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('compounded', models.BooleanField(default=False, verbose_name='manipulado')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor')),
                ('expiry_date', models.DateField(verbose_name='data de validade')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='doador')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.medicinetype', verbose_name='medicamento')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'doação de medicamento',
                'verbose_name_plural': 'doações de medicamento',
            },
        ),
        migrations.CreateModel(
            name='DonationAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('MED', 'Medicamento'), ('SAN', 'Sangue')], max_length=50, verbose_name='tipo de doação')),
                ('scheduled_date', models.DateTimeField(verbose_name='data agendada')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='doador')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'agendamento de doação',
                'verbose_name_plural': 'agendamentos de doação',
            },
        ),
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_type', models.CharField(max_length=50, verbose_name='tipo de bolsa')),
                ('bag_id', models.CharField(max_length=50, verbose_name='identificação da bolsa')),
                ('blood_type', models.CharField(max_length=50, verbose_name='tipo de sangue')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('validation_date', models.DateField(verbose_name='data de validação')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='doador')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipients.institution', verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'doação de sangue',
                'verbose_name_plural': 'doações de sangue',
            },
        ),
    ]
